### ISSUE TITLE
2.  Introduction

### ISSUE THREAD

**Issue by oguzkarademir** [aleks2407/HYF-TeamPower-project#7]
### Repository

- [x] developed on a branch called `introduction`

### HTML

- [x] A section element 
- [x] ... with an introduction to the page's main content
- [x] ... and class "introduction"

### CSS

- [x] the "introduction" class

**Comment by mametur** [comment]
I see your issue didn't connect to project, I just added you on there
@oguzkarademir  you can move your issue to the done column
